src/Entity/ToyRequest.php
<?php

namespace App\Entity;

use App\Repository\ToyRequestRepository;
use Carbon\Carbon;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;
use Symfony\Bridge\Doctrine\IdGenerator\UuidV4Generator;

/**
 * @ORM\Entity(repositoryClass=ToyRequestRepository::class)
 */
class ToyRequest
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidV4Generator::class)
     */
    private Uuid $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="toyRequests")
     */
    private User $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $name;

    /**
     * @ORM\Column(type="array")
     */
    private array $status = [];

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private DateTimeImmutable $createdAt;


    public function __construct()
    {
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?array
    {
        return $this->status;
    }

    public function setStatus(array $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedAtAgo(): string
    {
        return Carbon::instance($this->getCreatedAt())->diffForHumans();
    }
}

src/Controller/WorkFlowController.php
<?php

namespace App\Controller;

use App\Entity\ToyRequest;
use App\Form\ToyRequestType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Workflow\WorkflowInterface;

class WorkFlowController extends AbstractController
{

    public function __construct(private WorkflowInterface $toyRequestWorkflow)
    {
    }

    #[Route('/work/flow', name: 'work_flow')]
    public function index(): Response
    {
        return $this->render('work_flow/index.html.twig');
    }

    #[Route('/work/flow/new', name: 'work_flow_request')]
    public function workRequest(Request $request, EntityManagerInterface $entityManager): Response
    {
        $toy = new ToyRequest();

        $toy->setAuthor($this->getUser());

        $form = $this->createForm(ToyRequestType::class, $toy);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $toy = $form->getData();

            try {
                $this->toyRequestWorkflow->apply($toy, 'to_pending');
            } catch (\LogicException $e) {
            }


            $entityManager->persist($toy);
            $entityManager->flush();

            $this->addFlash('success', 'Demande enregistrée');


            return $this->redirectToRoute('work_flow');
        }


        return $this->render('work_flow/request.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/work/flow/demands', name: 'work_flow_demands')]
    public function demands(Request $request, EntityManagerInterface $entityManager): Response
    {

        return $this->render('work_flow/demand.html.twig', [
            'demands' => $entityManager->getRepository(ToyRequest::class)->findAll(),
        ]);
    }

    #[Route('/work/flow/change/{id}/{to}', name: 'work_flow_change')]
    public function change(ToyRequest $toyRequest, string $to, EntityManagerInterface $entityManager): Response
    {

        $test = $this->toyRequestWorkflow->getEnabledTransitions($toyRequest);
//        dd($test);

        try {
            $this->toyRequestWorkflow->apply($toyRequest, $to);
        } catch (\LogicException $e) {
            dd($e);
        }
//        dd($toyRequest);

        $entityManager->persist($toyRequest);
        $entityManager->flush();

        $this->addFlash('success', 'Action enregistrée');

        return  $this->redirectToRoute('work_flow_demands');
    }
}

templates/work_flow/demand.html.twig
{% extends 'base.html.twig' %}

{% block title %}WorkFlow{% endblock %}

{% block body %}

    <section id="featured">
        <div class="container max-viewport">
            <div class="row max-height-login justify-content-center align-items-center">


                <div class="col-10 mx-auto text-center">
                    <div class="card border border-danger shadow-lg">
                        <div class="card-header border-bottom border-danger bg-info">
                            Toutes les demandes
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Boy</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Date demand</th>
                                    <th scope="col">Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for demand in demands %}
                                    <tr>
                                        <th scope="row">{{ demand.author.nickname }}</th>
                                        <td>{{ demand.name }}</td>
                                        <td>{{ demand.createdAtAgo }}</td>
                                        <td>
{#                                                                                        {{ dump(workflow_transitions(demand)) }}#}
{#                                                                                        {{ dump(workflow_marked_places(demand)) }}#}

                                            {% if workflow_can(demand, 'to_dad_ok') %}
                                                <a
                                                        href="{{ path('work_flow_change', {'id': demand.id, 'to':'to_dad_ok' }) }}"
                                                        class="btn btn-outline-success"
                                                >
                                                    OK for dad
                                                </a>
                                            {% endif %}

                                            {% if workflow_can(demand, 'to_mum_ok') %}
                                                <a href="{{ path('work_flow_change', {id: demand.id, to:'to_mum_ok' }) }}"  class="btn btn-outline-success">OK for mum</a>
                                            {% endif %}

                                            {% if workflow_can(demand, 'to_order') %}
                                                <a href="{{ path('work_flow_change', {id: demand.id, to:'to_order' }) }}"  class="btn btn-outline-success">Order toy</a>
                                            {% endif %}

                                            {% if workflow_can(demand, 'to_ordered') %}
                                                <a href="{{ path('work_flow_change', {id: demand.id, to:'to_ordered' }) }}"  class="btn btn-outline-success">Ordered</a>
                                            {% endif %}

                                            {% if workflow_can(demand, 'to_received') %}
                                                <a href="{{ path('work_flow_change', {id: demand.id, to:'to_received' }) }}"  class="btn btn-outline-success">Toy received</a>
                                            {% endif %}

                                            {% if workflow_has_marked_place(demand, 'received') %}
                                                <p>The Toy is received</p>
                                            {% endif %}


                                            {% if workflow_has_marked_place(demand, 'dad_ok') and workflow_has_marked_place(demand, 'mum_validation_pending')  and is_granted('ROLE_DAD') %}
                                                <p>Attente de la Validation de maman</p>
                                            {% endif %}

                                            {% if workflow_has_marked_place(demand, 'mum_ok') and workflow_has_marked_place(demand, 'dad_validation_pending') and is_granted('ROLE_MUM') %}
                                                       <p>Attente de la Validation de papa</p>
                                            {% endif %}

                                        </td>

                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

{% endblock %}

templates/work_flow/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}WorkFlow{% endblock %}

{% block body %}

    <section id="featured">
        <div class="container max-viewport">
            <div class="row max-height-login justify-content-center align-items-center">
                <div class="col-10 mx-auto text-center">
                    <h1 class="text-uppercase"> Toy Request</h1>
                    <p class="text-muted">
                      Papa, maman, je veux un jouet ! Promet j'ai été super sage et j'ai fait tous mes devoirs !
                    </p>

                    <div>
                       <a href="{{ path('work_flow_request') }}" class="btn btn-outline-info">Demande un jouet !</a>
                       <a href="{{ path('work_flow_demands') }}" class="btn btn-outline-info">Traiter les demandes !</a>
                    </div>
                </div>
            </div>

        </div>
    </section>

{% endblock %}

templates/work_flow/request.html.twig
{% extends 'base.html.twig' %}

{% block title %}WorkFlow{% endblock %}

{% block body %}

    <section id="featured">
        <div class="container max-viewport">
            <div class="row max-height-login justify-content-center align-items-center">




                <div class="col-10 mx-auto text-center">
                    <div class="card border border-danger shadow-lg">
                        <div class="card-header border-bottom border-danger bg-info">
                            Toutes les demandes
                        </div>
                        <div class="card-body">
                            {{ form(form) }}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

{% endblock %}